### ISSUE TITLE
chemical_component_sets.pickle missing

### ISSUE THREAD

**Issue by FlorianWieser1** [Kuhlman-Lab/alphafold3#13]
Thanks a lot for this project! :)

I could compile it without issues, however when i try to run the first example on Top7, I get - FileNotFoundError: [Errno 2] No such file or directory: '/home/florian_wieser/.conda/envs/af3/lib/python3.11/site-packages/alphafold3/constants/converters/chemical_component_sets.pickle'. And indeed, i don't have any pickle files in this path, just chemical_component_sets_gen.py and ccd_pickle_gen.py. What am I missing? 
Thank you in advance!

**Comment by nzrandol** [comment]
Hi! I think that that pickle file should be created when running `build_data` in step 8 of the installation. The `build_data` command should have been added to your PATH after running step 7, so if it's not there you may have to re-run that too. Let me know if that helps!

**Comment by FlorianWieser1** [comment]
Thank for the quick answer! Rerunning build_data fixed it for me and I can run the model now. However, I get spaghetti on a Tesla T4 gpu with xla attention. Do you know if T4 is supported at all? Thanks in advance! (P.S. I successfully ran it on a system with an A100 card, so I got the installation procedure) 
![2024-12-05_12-25](https://github.com/user-attachments/assets/e347e86a-cbed-41b8-907c-e161aca0f73c)

**Comment by nzrandol** [comment]
Great to hear that it seems to be working now! I haven't tried using a T4 GPU, but based on [this](https://github.com/google-deepmind/alphafold3/pull/114#issue-2688048005), I'd expect it to produce noise like what you see. 

Gonna close this issue, but feel free to re-open or create a new one!

**Comment by nzrandol** [comment]
I recently merged some changes that _may_ help with GPUs with a CUDA compute capability of 7.x. Maybe it'll make the outputs on the T4 more sensible? Please try adding `--cuda_compute_7x 1`, and let me know how it works!

**Comment by cweasel33** [comment]
Dear nzrandol,
works now with your new option. Thanks a lot!
