### ISSUE TITLE
run_af3.py has hardcoded paths

### ISSUE THREAD

**Issue by gezmi** [Kuhlman-Lab/alphafold3#18]
Hi,

At lines 602 and 603, two hardcoded paths are in the file, which needs to be manually edited. I guess this is a mistake, just thought I would notify the developers.

Thanks for putting this together, running with the mmseqs2 server makes life lot easier!

**Comment by nzrandol** [comment]
Hi! I can't seem to find the hardcoded paths in `run_af3.py` you're referencing. Could you please provide links directly to the lines?
